// SSH host alias allowlist.
//
// Stores accepted ~/.ssh/config aliases (one per line) under
// taiji-output/state/allowed-hosts.txt. Comments start with '#'.
// auto-loop.mjs and the guard-bash.sh PreToolUse hook both consult this
// list before allowing any ssh / scp / rsync command, so the user has a
// single place to grant or revoke remote-host access without hunting
// through code.
//
// Aliases must match /^[A-Za-z0-9_.\-]+$/ — refusing user@host and raw
// IPs at the source rules out the simplest credential-leak shape (full
// connection string in CLI args / process tables / shell history).

import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
export const DEFAULT_ALLOWLIST_PATH = path.join(ROOT, "taiji-output", "state", "allowed-hosts.txt");

const ALIAS_REGEX = /^[A-Za-z0-9_.\-]+$/;

export function isValidAlias(alias) {
  if (typeof alias !== "string") return false;
  if (!ALIAS_REGEX.test(alias)) return false;
  if (alias.includes("@")) return false; // user@host shape forbidden
  if (alias === "." || alias === "..") return false; // path-traversal segments
  return true;
}

export async function readAllowedHosts(allowlistPath = DEFAULT_ALLOWLIST_PATH) {
  let text;
  try {
    text = await readFile(allowlistPath, "utf8");
  } catch (error) {
    if (error.code === "ENOENT") return [];
    throw error;
  }
  return text
    .split(/\r?\n/)
    .map((line) => line.replace(/#.*$/, "").trim())
    .filter(Boolean);
}

export async function isHostAllowed(alias, allowlistPath = DEFAULT_ALLOWLIST_PATH) {
  if (!isValidAlias(alias)) return false;
  const allowlist = await readAllowedHosts(allowlistPath);
  return allowlist.includes(alias);
}

export async function assertHostAllowed(alias, allowlistPath = DEFAULT_ALLOWLIST_PATH) {
  if (!isValidAlias(alias)) {
    throw new Error(`Refusing host alias '${alias}': must match ${ALIAS_REGEX} and not contain '@'.`);
  }
  const allowlist = await readAllowedHosts(allowlistPath);
  if (!allowlist.includes(alias)) {
    throw new Error(`Host alias '${alias}' is not in ${allowlistPath}. Add it explicitly to enable SSH/SCP/RSYNC against this host.`);
  }
}

export async function appendAllowedHost(alias, allowlistPath = DEFAULT_ALLOWLIST_PATH) {
  if (!isValidAlias(alias)) {
    throw new Error(`Invalid alias: ${alias}`);
  }
  const current = await readAllowedHosts(allowlistPath);
  if (current.includes(alias)) return { added: false, allowlist: current };
  const next = [...current, alias];
  await mkdir(path.dirname(allowlistPath), { recursive: true });
  const stamp = new Date().toISOString();
  const block = `${current.length ? "" : `# allowed-hosts.txt — one ssh-config alias per line.\n# Generated by taac2026; edit by hand to add/remove.\n`}# added ${stamp}\n${alias}\n`;
  // Re-render the whole file to keep deterministic ordering.
  const header = `# allowed-hosts.txt — SSH host aliases authorized for taac2026 loop.\n# One alias per line; blank lines and # comments allowed.\n# Generated/maintained by taac2026; edit by hand to add or remove entries.\n#\n`;
  await writeFile(allowlistPath, header + next.map((a) => `${a}\n`).join(""), "utf8");
  return { added: true, allowlist: next };
}

export { ALIAS_REGEX };
